# Generated by Django 6.1 on 2026-09-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chorecompletion",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
